//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsApp.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Business.
        /// </summary>
        public static string Categories_Business {
            get {
                return ResourceManager.GetString("Categories_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entertainment.
        /// </summary>
        public static string Categories_Entertainment {
            get {
                return ResourceManager.GetString("Categories_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Health.
        /// </summary>
        public static string Categories_Health {
            get {
                return ResourceManager.GetString("Categories_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Science.
        /// </summary>
        public static string Categories_Science {
            get {
                return ResourceManager.GetString("Categories_Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sports.
        /// </summary>
        public static string Categories_Sports {
            get {
                return ResourceManager.GetString("Categories_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Technology.
        /// </summary>
        public static string Categories_Technology {
            get {
                return ResourceManager.GetString("Categories_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AE.
        /// </summary>
        public static string Countries_AE {
            get {
                return ResourceManager.GetString("Countries_AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AR.
        /// </summary>
        public static string Countries_AR {
            get {
                return ResourceManager.GetString("Countries_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AT.
        /// </summary>
        public static string Countries_AT {
            get {
                return ResourceManager.GetString("Countries_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AU.
        /// </summary>
        public static string Countries_AU {
            get {
                return ResourceManager.GetString("Countries_AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BE.
        /// </summary>
        public static string Countries_BE {
            get {
                return ResourceManager.GetString("Countries_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BG.
        /// </summary>
        public static string Countries_BG {
            get {
                return ResourceManager.GetString("Countries_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BR.
        /// </summary>
        public static string Countries_BR {
            get {
                return ResourceManager.GetString("Countries_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CA.
        /// </summary>
        public static string Countries_CA {
            get {
                return ResourceManager.GetString("Countries_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CH.
        /// </summary>
        public static string Countries_CH {
            get {
                return ResourceManager.GetString("Countries_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CN.
        /// </summary>
        public static string Countries_CN {
            get {
                return ResourceManager.GetString("Countries_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CO.
        /// </summary>
        public static string Countries_CO {
            get {
                return ResourceManager.GetString("Countries_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CU.
        /// </summary>
        public static string Countries_CU {
            get {
                return ResourceManager.GetString("Countries_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CZ.
        /// </summary>
        public static string Countries_CZ {
            get {
                return ResourceManager.GetString("Countries_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DE.
        /// </summary>
        public static string Countries_DE {
            get {
                return ResourceManager.GetString("Countries_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EG.
        /// </summary>
        public static string Countries_EG {
            get {
                return ResourceManager.GetString("Countries_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FR.
        /// </summary>
        public static string Countries_FR {
            get {
                return ResourceManager.GetString("Countries_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GB.
        /// </summary>
        public static string Countries_GB {
            get {
                return ResourceManager.GetString("Countries_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GR.
        /// </summary>
        public static string Countries_GR {
            get {
                return ResourceManager.GetString("Countries_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HK.
        /// </summary>
        public static string Countries_HK {
            get {
                return ResourceManager.GetString("Countries_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HU.
        /// </summary>
        public static string Countries_HU {
            get {
                return ResourceManager.GetString("Countries_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Countries_ID {
            get {
                return ResourceManager.GetString("Countries_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IE.
        /// </summary>
        public static string Countries_IE {
            get {
                return ResourceManager.GetString("Countries_IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IL.
        /// </summary>
        public static string Countries_IL {
            get {
                return ResourceManager.GetString("Countries_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IN.
        /// </summary>
        public static string Countries_IN {
            get {
                return ResourceManager.GetString("Countries_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IT.
        /// </summary>
        public static string Countries_IT {
            get {
                return ResourceManager.GetString("Countries_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JP.
        /// </summary>
        public static string Countries_JP {
            get {
                return ResourceManager.GetString("Countries_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KR.
        /// </summary>
        public static string Countries_KR {
            get {
                return ResourceManager.GetString("Countries_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LT.
        /// </summary>
        public static string Countries_LT {
            get {
                return ResourceManager.GetString("Countries_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LV.
        /// </summary>
        public static string Countries_LV {
            get {
                return ResourceManager.GetString("Countries_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MA.
        /// </summary>
        public static string Countries_MA {
            get {
                return ResourceManager.GetString("Countries_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MX.
        /// </summary>
        public static string Countries_MX {
            get {
                return ResourceManager.GetString("Countries_MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MY.
        /// </summary>
        public static string Countries_MY {
            get {
                return ResourceManager.GetString("Countries_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NG.
        /// </summary>
        public static string Countries_NG {
            get {
                return ResourceManager.GetString("Countries_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NL.
        /// </summary>
        public static string Countries_NL {
            get {
                return ResourceManager.GetString("Countries_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NO.
        /// </summary>
        public static string Countries_NO {
            get {
                return ResourceManager.GetString("Countries_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NZ.
        /// </summary>
        public static string Countries_NZ {
            get {
                return ResourceManager.GetString("Countries_NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PH.
        /// </summary>
        public static string Countries_PH {
            get {
                return ResourceManager.GetString("Countries_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PL.
        /// </summary>
        public static string Countries_PL {
            get {
                return ResourceManager.GetString("Countries_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PT.
        /// </summary>
        public static string Countries_PT {
            get {
                return ResourceManager.GetString("Countries_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RO.
        /// </summary>
        public static string Countries_RO {
            get {
                return ResourceManager.GetString("Countries_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RS.
        /// </summary>
        public static string Countries_RS {
            get {
                return ResourceManager.GetString("Countries_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RU.
        /// </summary>
        public static string Countries_RU {
            get {
                return ResourceManager.GetString("Countries_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SA.
        /// </summary>
        public static string Countries_SA {
            get {
                return ResourceManager.GetString("Countries_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SE.
        /// </summary>
        public static string Countries_SE {
            get {
                return ResourceManager.GetString("Countries_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SG.
        /// </summary>
        public static string Countries_SG {
            get {
                return ResourceManager.GetString("Countries_SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SI.
        /// </summary>
        public static string Countries_SI {
            get {
                return ResourceManager.GetString("Countries_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SK.
        /// </summary>
        public static string Countries_SK {
            get {
                return ResourceManager.GetString("Countries_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TH.
        /// </summary>
        public static string Countries_TH {
            get {
                return ResourceManager.GetString("Countries_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TR.
        /// </summary>
        public static string Countries_TR {
            get {
                return ResourceManager.GetString("Countries_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TW.
        /// </summary>
        public static string Countries_TW {
            get {
                return ResourceManager.GetString("Countries_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UA.
        /// </summary>
        public static string Countries_UA {
            get {
                return ResourceManager.GetString("Countries_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US.
        /// </summary>
        public static string Countries_US {
            get {
                return ResourceManager.GetString("Countries_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VE.
        /// </summary>
        public static string Countries_VE {
            get {
                return ResourceManager.GetString("Countries_VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ZA.
        /// </summary>
        public static string Countries_ZA {
            get {
                return ResourceManager.GetString("Countries_ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        public static string Country_Label {
            get {
                return ResourceManager.GetString("Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string Filters_TextBlock {
            get {
                return ResourceManager.GetString("Filters_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string From_Label {
            get {
                return ResourceManager.GetString("From_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrectly set time interval.
        /// </summary>
        public static string IncorrectTimeSpan {
            get {
                return ResourceManager.GetString("IncorrectTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Localization.
        /// </summary>
        public static string Localization_Label {
            get {
                return ResourceManager.GetString("Localization_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string Localizations_en {
            get {
                return ResourceManager.GetString("Localizations_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukrainian.
        /// </summary>
        public static string Localizations_uk {
            get {
                return ResourceManager.GetString("Localizations_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News.
        /// </summary>
        public static string News_TextBlock {
            get {
                return ResourceManager.GetString("News_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search_Button {
            get {
                return ResourceManager.GetString("Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        public static string SortBy_Label {
            get {
                return ResourceManager.GetString("SortBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Popularity.
        /// </summary>
        public static string SortBys_Popularity {
            get {
                return ResourceManager.GetString("SortBys_Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PublishedAt.
        /// </summary>
        public static string SortBys_PublishedAt {
            get {
                return ResourceManager.GetString("SortBys_PublishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relevancy.
        /// </summary>
        public static string SortBys_Relevancy {
            get {
                return ResourceManager.GetString("SortBys_Relevancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time span.
        /// </summary>
        public static string TimeSpan_CheckBox {
            get {
                return ResourceManager.GetString("TimeSpan_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string To_Label {
            get {
                return ResourceManager.GetString("To_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top headlines.
        /// </summary>
        public static string TopHeadlines_TextBlock {
            get {
                return ResourceManager.GetString("TopHeadlines_TextBlock", resourceCulture);
            }
        }
    }
}
